/LF/controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    reboot_controller:
      type: forward_command_controller/ForwardCommandController

/LF/joint_trajectory_controller:
  ros__parameters:
    joints:
      - LF_B2C
      - LF_C2F
      - LF_F2T
      - LF_T2E

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0  # [Hz]
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false  # true: no feedback, false: use feedback
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.001
      goal_time: 0.0

    gains:
      LF_B2C:
        p: 10.0
        i: 0.0
        d: 0.1
        ff_velocity_scale: 1.0
      LF_C2F:
        p: 10.0
        i: 0.0
        d: 0.1
        ff_velocity_scale: 1.0
      LF_F2T:
        p: 10.0
        i: 0.0
        d: 0.1
        ff_velocity_scale: 1.0
      LF_T2E:
        p: 10.0
        i: 0.0
        d: 0.1
        ff_velocity_scale: 1.0

/LF/gripper_controller:
  ros__parameters:
    joints:
      - LF_gripper_joint
    interface_name: velocity

/LF/reboot_controller:
  ros__parameters:
    joints:
      - LF_B2C
      - LF_C2F
      - LF_F2T
      - LF_T2E
      - LF_E2G
      - LF_gripper_joint

    interface_name: reboot
